#!/usr/bin/env bash

# Print "bad luck" during the 4th loop iteration
# Print "good luck" during the 8th
# Print "Best School" for others

i=1

while [ $i -lt 11 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
