#!/usr/bin/env bash
# Check if school file exists and provides information about it.
# If the file exists, it checks if it's empty or not(if it is a regular file or not).

if [ -e school ]; then
    echo "school file exists"
    if [ -s school ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    if [ -f school ]; then
        echo "school is a regular file"
    fi

else
    echo "school file does not exist"
fi
